var n=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}},p=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):{next:n(a)}},aa="function"==typeof Object.create?Object.create:function(a){var c=function(){};c.prototype=a;return new c},q;
if("function"==typeof Object.setPrototypeOf)q=Object.setPrototypeOf;else{var u;a:{var ba={w:!0},v={};try{v.__proto__=ba;u=v.w;break a}catch(a){}u=!1}q=u?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null}
var x=q,y=function(a,c){a.prototype=aa(c.prototype);a.prototype.constructor=a;if(x)x(a,c);else for(var d in c)if("prototype"!=d)if(Object.defineProperties){var g=Object.getOwnPropertyDescriptor(c,d);g&&Object.defineProperty(a,d,g)}else a[d]=c[d];a.A=c.prototype},z="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,A="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)},
B=function(){B=function(){};z.Symbol||(z.Symbol=ca)},C=function(a,c){this.a=a;A(this,"description",{configurable:!0,writable:!0,value:c})};C.prototype.toString=function(){return this.a};
var ca=function(){function a(d){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new C("jscomp_symbol_"+(d||"")+"_"+c++,d)}var c=0;return a}(),E=function(){B();var a=z.Symbol.iterator;a||(a=z.Symbol.iterator=z.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&A(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return D(n(this))}});E=function(){}},D=function(a){E();a={next:a};a[z.Symbol.iterator]=function(){return this};return a},F=function(a,
c){return Object.prototype.hasOwnProperty.call(a,c)},I=function(a,c){if(c){var d=z;a=a.split(".");for(var g=0;g<a.length-1;g++){var k=a[g];k in d||(d[k]={});d=d[k]}a=a[a.length-1];g=d[a];c=c(g);c!=g&&null!=c&&A(d,a,{configurable:!0,writable:!0,value:c})}};
I("WeakMap",function(a){function c(){}function d(b){if(!F(b,k)){var e=new c;A(b,k,{value:e})}}function g(b){var e=Object[b];e&&(Object[b]=function(h){if(h instanceof c)return h;d(h);return e(h)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),e=Object.seal({}),h=new a([[b,2],[e,3]]);if(2!=h.get(b)||3!=h.get(e))return!1;h["delete"](b);h.set(e,4);return!h.has(b)&&4==h.get(e)}catch(m){return!1}}())return a;var k="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");
g("seal");var l=0,f=function(b){this.a=(l+=Math.random()+1).toString();if(b){b=p(b);for(var e;!(e=b.next()).done;)e=e.value,this.set(e[0],e[1])}};f.prototype.set=function(b,e){d(b);if(!F(b,k))throw Error("WeakMap key fail: "+b);b[k][this.a]=e;return this};f.prototype.get=function(b){return F(b,k)?b[k][this.a]:void 0};f.prototype.has=function(b){return F(b,k)&&F(b[k],this.a)};f.prototype["delete"]=function(b){return F(b,k)&&F(b[k],this.a)?delete b[k][this.a]:!1};return f});
I("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),e=new a(p([[b,"s"]]));if("s"!=e.get(b)||1!=e.size||e.get({x:4})||e.set({x:4},"t")!=e||2!=e.size)return!1;var h=e.entries(),m=h.next();if(m.done||m.value[0]!=b||"s"!=m.value[1])return!1;m=h.next();return m.done||4!=m.value[0].x||"t"!=m.value[1]||!h.next().done?!1:!0}catch(r){return!1}}())return a;E();var c=new WeakMap,d=function(b){this.b={};this.a=
l();this.size=0;if(b){b=p(b);for(var e;!(e=b.next()).done;)e=e.value,this.set(e[0],e[1])}};d.prototype.set=function(b,e){b=0===b?0:b;var h=g(this,b);h.list||(h.list=this.b[h.id]=[]);h.entry?h.entry.value=e:(h.entry={next:this.a,previous:this.a.previous,head:this.a,key:b,value:e},h.list.push(h.entry),this.a.previous.next=h.entry,this.a.previous=h.entry,this.size++);return this};d.prototype["delete"]=function(b){b=g(this,b);return b.entry&&b.list?(b.list.splice(b.index,1),b.list.length||delete this.b[b.id],
b.entry.previous.next=b.entry.next,b.entry.next.previous=b.entry.previous,b.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.b={};this.a=this.a.previous=l();this.size=0};d.prototype.has=function(b){return!!g(this,b).entry};d.prototype.get=function(b){return(b=g(this,b).entry)&&b.value};d.prototype.entries=function(){return k(this,function(b){return[b.key,b.value]})};d.prototype.keys=function(){return k(this,function(b){return b.key})};d.prototype.values=function(){return k(this,
function(b){return b.value})};d.prototype.forEach=function(b,e){for(var h=this.entries(),m;!(m=h.next()).done;)m=m.value,b.call(e,m[1],m[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var g=function(b,e){var h=e&&typeof e;"object"==h||"function"==h?c.has(e)?h=c.get(e):(h=""+ ++f,c.set(e,h)):h="p_"+e;var m=b.b[h];if(m&&F(b.b,h))for(b=0;b<m.length;b++){var r=m[b];if(e!==e&&r.key!==r.key||e===r.key)return{id:h,list:m,index:b,entry:r}}return{id:h,list:m,index:-1,entry:void 0}},k=function(b,
e){var h=b.a;return D(function(){if(h){for(;h.head!=b.a;)h=h.previous;for(;h.next!=h.head;)return h=h.next,{done:!1,value:e(h)};h=null}return{done:!0,value:void 0}})},l=function(){var b={};return b.previous=b.next=b.head=b},f=0;return d});
I("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var d=Object.seal({x:4}),g=new a(p([d]));if(!g.has(d)||1!=g.size||g.add(d)!=g||1!=g.size||g.add({x:4})!=g||2!=g.size)return!1;var k=g.entries(),l=k.next();if(l.done||l.value[0]!=d||l.value[1]!=d)return!1;l=k.next();return l.done||l.value[0]==d||4!=l.value[0].x||l.value[1]!=l.value[0]?!1:k.next().done}catch(f){return!1}}())return a;E();var c=function(d){this.a=new Map;if(d){d=
p(d);for(var g;!(g=d.next()).done;)this.add(g.value)}this.size=this.a.size};c.prototype.add=function(d){d=0===d?0:d;this.a.set(d,d);this.size=this.a.size;return this};c.prototype["delete"]=function(d){d=this.a["delete"](d);this.size=this.a.size;return d};c.prototype.clear=function(){this.a.clear();this.size=0};c.prototype.has=function(d){return this.a.has(d)};c.prototype.entries=function(){return this.a.entries()};c.prototype.values=function(){return this.a.values()};c.prototype.keys=c.prototype.values;
c.prototype[Symbol.iterator]=c.prototype.values;c.prototype.forEach=function(d,g){var k=this;this.a.forEach(function(l){return d.call(g,l,l,k)})};return c});
I("Promise",function(a){function c(){this.a=null}function d(f){return f instanceof k?f:new k(function(b){b(f)})}if(a)return a;c.prototype.b=function(f){if(null==this.a){this.a=[];var b=this;this.c(function(){b.g()})}this.a.push(f)};var g=z.setTimeout;c.prototype.c=function(f){g(f,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var f=this.a;this.a=[];for(var b=0;b<f.length;++b){var e=f[b];f[b]=null;try{e()}catch(h){this.f(h)}}}this.a=null};c.prototype.f=function(f){this.c(function(){throw f;
})};var k=function(f){this.b=0;this.g=void 0;this.a=[];var b=this.c();try{f(b.resolve,b.reject)}catch(e){b.reject(e)}};k.prototype.c=function(){function f(h){return function(m){e||(e=!0,h.call(b,m))}}var b=this,e=!1;return{resolve:f(this.s),reject:f(this.f)}};k.prototype.s=function(f){if(f===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof k)this.u(f);else{a:switch(typeof f){case "object":var b=null!=f;break a;case "function":b=!0;break a;default:b=!1}b?this.o(f):
this.j(f)}};k.prototype.o=function(f){var b=void 0;try{b=f.then}catch(e){this.f(e);return}"function"==typeof b?this.v(b,f):this.j(f)};k.prototype.f=function(f){this.l(2,f)};k.prototype.j=function(f){this.l(1,f)};k.prototype.l=function(f,b){if(0!=this.b)throw Error("Cannot settle("+f+", "+b+"): Promise already settled in state"+this.b);this.b=f;this.g=b;this.m()};k.prototype.m=function(){if(null!=this.a){for(var f=0;f<this.a.length;++f)l.b(this.a[f]);this.a=null}};var l=new c;k.prototype.u=function(f){var b=
this.c();f.i(b.resolve,b.reject)};k.prototype.v=function(f,b){var e=this.c();try{f.call(b,e.resolve,e.reject)}catch(h){e.reject(h)}};k.prototype.then=function(f,b){function e(t,w){return"function"==typeof t?function(G){try{h(t(G))}catch(H){m(H)}}:w}var h,m,r=new k(function(t,w){h=t;m=w});this.i(e(f,h),e(b,m));return r};k.prototype["catch"]=function(f){return this.then(void 0,f)};k.prototype.i=function(f,b){function e(){switch(h.b){case 1:f(h.g);break;case 2:b(h.g);break;default:throw Error("Unexpected state: "+
h.b);}}var h=this;null==this.a?l.b(e):this.a.push(e)};k.resolve=d;k.reject=function(f){return new k(function(b,e){e(f)})};k.race=function(f){return new k(function(b,e){for(var h=p(f),m=h.next();!m.done;m=h.next())d(m.value).i(b,e)})};k.all=function(f){var b=p(f),e=b.next();return e.done?d([]):new k(function(h,m){function r(G){return function(H){t[G]=H;w--;0==w&&h(t)}}var t=[],w=0;do t.push(void 0),w++,d(e.value).i(r(t.length-1),m),e=b.next();while(!e.done)})};return k});
I("Array.from",function(a){return a?a:function(c,d,g){d=null!=d?d:function(b){return b};var k=[],l="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];if("function"==typeof l){c=l.call(c);for(var f=0;!(l=c.next()).done;)k.push(d.call(g,l.value,f++))}else for(l=c.length,f=0;f<l;f++)k.push(d.call(g,c[f],f));return k}});var da=this||self;var J=new Set;var K=function(a){this.locked=a},ea=function(a){this.response=a},L=function(a){this.errorType=a},M=function(a){this.errorType="This Chrome API is not available";this.call=a};y(M,L);var N=function(a,c){this.errorType="Error executing Chrome API";this.call=a;this.message=c};y(N,L);var O=function(){this.errorType="Tab is not locked"};y(O,L);var P=function(){this.errorType="Devtools cannot be open when locking"};y(P,L);var Q=function(){this.errorType="Unknown command"};y(Q,L);
var R=function(a){this.errorType="Unknown Error";this.exception=fa(a)};y(R,L);function fa(a){var c={};Object.getOwnPropertyNames(a).forEach(function(d){c[d]=a[d]});return c};var S=function(a){for(var c=da,d=p(a.split(".")),g=d.next();!g.done;g=d.next())if(c=c[g.value],void 0==c)return function(){return Promise.reject(new M(a))};return function(k){var l=Array.prototype.slice.call(arguments);return new Promise(function(f,b){l.push(function(e){if(chrome.runtime.lastError)b(new N(a,chrome.runtime.lastError.message));else switch(arguments.length){case 0:f(void 0);break;case 1:f(arguments[0]);break;default:f(Array.prototype.slice.call(arguments))}});c.apply(null,l)})}};var T=new function(){this.f=S("chrome.tabs.discard");this.s=S("chrome.tabs.query");this.o=S("chrome.tabs.move");this.u=S("chrome.tabs.reload");this.v=S("chrome.tabs.update");this.a=S("chrome.windows.create");this.j=S("chrome.windows.getCurrent");this.l=S("chrome.windows.get");this.c=S("chrome.windows.update");this.m=S("chrome.enterprise.platformKeys.challengeMachineKey");this.g=S("chrome.management.getAll");this.b=S("chrome.management.setEnabled")};var ha=new Set("gndmhdcefbhlchkhipcnnbkcmicncehk ifajfiofeifbbhbionejdliodenmecna imgmjcnolbhljlnimjbnmeokfljgjokj haldlgldplgnggkjaafhelgiaglafanh hjngolefdpdnooamgdldlkjgmdcmcjnc ckanlcmoklgdobgbkebohpficpiogcif kbohafcopfpigkjdimdcdgenlhkmhbnc hmfjajhcddnpmhkhakkgoibealjcffho kmffehbidlalibfeklaefnckpidbodff fabpdabkjmplhckhfhknoemeihjffobe mnehmlglkdbpcimikacjgegmpebacoab inoeonmfapjbbkmdafoankkfajkcphgd ikfigngpioedjjooplekefdiilaokaik iheobagjkfklnlikgihanlhcddjoihkg mloajfnmjckfjbeeofcdaecbelnblden emmgndmggimgmmpciejhnkcnlillakfn".split(" ")),
U,V;U=new Set(JSON.parse(window.localStorage.getItem("disabledExtensions")||"[]"));V=Promise.resolve();function W(){window.localStorage.setItem("disabledExtensions",JSON.stringify(Array.from(U)))}
var ia=function(){return V=V.then(function(){return T.g().then(function(a){a=a.filter(function(g){return!ha.has(g.id)&&g.enabled&&"extension"==g.type}).map(function(g){return g.id});for(var c=p(a),d=c.next();!d.done;d=c.next())U.add(d.value);W();a=a.map(function(g){return T.b(g,!1)["catch"](function(){console.warn("Error disabling "+g);U["delete"](g)})});return Promise.all(a).then(W)})})},X=function(){return V=V.then(function(){for(var a=[],c={},d=p(U),g=d.next();!g.done;c={h:c.h},g=d.next())c.h=
g.value,a.push(T.b(c.h,!0).then(function(k){return function(){return U["delete"](k.h)}}(c)));return Promise.all(a).then(W)})};var ja=function(a){return T.s({discarded:!1}).then(function(c){return Promise.all(c.filter(function(d){return d.id!=a}).map(function(d){return T.f(d.id)}))})};function Y(){return JSON.parse(window.localStorage.getItem("savedTab")||"null")}function Z(a){window.localStorage.setItem("savedTab",JSON.stringify(a))}
var ka=Promise.resolve(),ma=function(a){if(J.has(a.id))throw console.warn("Devtools detected in tab "+a.id),new P;return T.a({type:"popup",state:"fullscreen",tabId:a.id,incognito:a.incognito}).then(function(c){return T.c(c.id,{state:"locked-fullscreen"})}).then(function(){Z(a);return Promise.all([ja(a.id),ia()])})["catch"](function(c){return la(a).then(function(){throw c;})}).then(function(){ka=T.u(a.id);return new K(!0)})},na=function(a){var c=Y();if(null==c||c.id!=a.id)throw new O;return la(c).then(function(){return new K(!1)})};
function la(a){Z(null);return Promise.all([X(),T.j().then(function(c){return T.c(c.id,{state:"fullscreen"})}).then(function(){return T.l(a.windowId)}).then(function(){return T.o(a.id,{index:a.index,windowId:a.windowId}).then(function(c){return T.v(c.id,{active:!0})})},function(){return T.a({type:"normal",state:"normal",tabId:a.id,incognito:a.incognito})})])}function oa(a){var c=Y();return!!c&&c.id==a.id};var qa=function(a,c){if(oa(a))a=ka;else throw new O;return a.then(function(){return T.m(pa(c))}).then(function(d){var g="";d=new Uint8Array(d);for(var k=d.byteLength,l=0;l<k;l++)g+=String.fromCharCode(d[l]);g=window.btoa(g);return new ea(g)})};function pa(a){a=window.atob(a);for(var c=a.length,d=new Uint8Array(c),g=0;g<c;g++)d[g]=a.charCodeAt(g);return d.buffer};function ra(a,c){console.error(a);a instanceof L?c(a):c(new R(a))};chrome.runtime.onConnect.addListener(function(a){var c=parseInt(a.name,10);J.add(c);a.onDisconnect.addListener(function(){J["delete"](c)})});chrome.runtime.onStartup.addListener(X);
chrome.runtime.onMessageExternal.addListener(function(a,c,d){if(c.tab)try{switch(a.command){case "lock":var g=ma(c.tab);break;case "isLocked":g=Promise.resolve(new K(oa(c.tab)));break;case "unlock":g=na(c.tab);break;case "challenge":g=qa(c.tab,a.challenge);break;default:throw new Q;}g.then(function(k){return d(k)},function(k){return ra(k,d)});return!0}catch(k){ra(k,d)}});
